services:
  redis:
    container_name: pickple-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/docker/volumes/redis/_data:/data
      - /var/lib/docker/volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf